[workspace]
members = ["client", "server"]

[workspace.package]
version = "1.0.0"
edition = "2018"
authors = ["Kacper Skelnik"]

[workspace.dependencies]
tokio = { version = "1.35.1", features = ["full"] }